### ISSUE TITLE
Getting a Jquery error

### ISSUE THREAD

**Issue by CamKelly** [creativetimofficial/ct-material-kit-pro#14]
jQuery.Deferred exception: Cannot read property 'nodeName' of null TypeError: Cannot read property 'nodeName' of null
    at Object.S [as create] (http://localhost:4200/assets/js/nouislider.min.js:3:18056)
    at HTMLDocument.<anonymous> (http://localhost:4200/login?returnUrl=%2F:64:18)
    at j (http://localhost:4200/assets/js/jquery.min.js:2:29948)
    at k (http://localhost:4200/assets/js/jquery.min.js:2:30262)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:3239:31)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:3006:47)
    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:3301:38)
    at timer (http://localhost:4200/polyfills.bundle.js:4381:29) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
zone.js:169 Uncaught TypeError: Cannot read property 'nodeName' of null
    at Object.S [as create] (nouislider.min.js:3)
    at HTMLDocument.<anonymous> (login?returnUrl=%2F:64)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
    at ZoneDelegate.invokeTask (zone.js:398)
    at Zone.runTask (zone.js:165)
    at ZoneTask.invoke (zone.js:460)
    at timer (zone.js:1540)

**Comment by alexandru-paduraru** [comment]
@CamKelly thank you for using our product and sorry for the late response. 

1. Can you please give us more details about what are you building? 
2. What Framework do you use? Is Angular or something? 
3. How is the structure of files? Do you have a link or a repo so we can check?

We need more information to reproduce this error on our systems. 

Best,
Alex

**Comment by CamKelly** [comment]
I'm using the angular 2 seed ($ ng new ctim). Then I added the assets folder and necessary entries to the index.html page. Next, using 'ng serve', I get the above error when I look in the console of chromes developer tools.

Public repo is here:

(https://github.com/CamKelly/ctim)

**Comment by alexandru-paduraru** [comment]
Hi @CamKelly we've checked and on our side everything is working fine with npm install and npm serve
<img width="543" alt="screen shot 2017-05-19 at 12 46 24" src="https://cloud.githubusercontent.com/assets/2517758/26242487/49917ba2-3c91-11e7-877d-c1ea9bcc080a.png">
:

<img width="773" alt="screen shot 2017-05-19 at 12 46 27" src="https://cloud.githubusercontent.com/assets/2517758/26242481/43ac10a8-3c91-11e7-9a2f-223d38755f67.png">

Do you have all the dependencies installed and npm correctly?

Please also check how one of our users is working with our LBD Free on Angular CLI and how he added the scripts: https://github.com/bonnici/light-bootstrap-dashboard-angularcli

Best,
Alex
